### ISSUE TITLE
Cant raise TypeError (or ValueError)

### ISSUE THREAD

**Issue by ps178** [Duke-BME-Design/Ouroboros_testing#5]
I'm using numpy.amax(my_list) , and similarly amin, to get the max and min values from the list. I set the try except for TypeError however I cant figure out how to induce the TypeError. I tried to find documentation for "amax" to determine what input would cause a TypeError but couldnt find anything. I tried inputting a string and inputting none but neither seems to raise TypeError.

**Comment by mlp6** [comment]
This is what I get when I input a list of strings (characters):

**Comment by ps178** [comment]
Oh. So my test still keeps failing due to "UnboundLocalError: local variable 'max_min' referenced before assignment". Is that because when I dont have the correct type of input there is nothing to assign to the variable max_min? 

def return_min_max(my_list):

try:
    max_min = ((np.amax(my_list), np.amin(my_list)))
except TypeError:
    logging.debug('my_list is ...')
    print("You did not input a list of numbers")
except ValueError:
    print("The input type is correct but inappropriate")
return max_min

**Comment by mlp6** [comment]
```
local variable 'max_min' referenced before assignment
```
That part of the error message leads me to believe that a chunk of your code is trying to use a variable that doesn't yet exist, which is triggering the error message you you see, as you thought.

**Comment by ps178** [comment]
So, after some unnecessary hours of repetitive work I have come to realize that if I do not add any try&except statements then my test passes with flying colours where inputting a string raises a TypeError and inputting an empty list raises a ValueError. If I add try&except to my module with except TypeError and except Value error then the exact same test will fail claiming that TypeError and ValueError were not raised. :(

**Comment by ps178** [comment]
Ok, I got it to work but I have a lot of questions about it that I will ask later
